version: 'three-point-zero'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=abter
      - MYSQL_USER=abter
      - MYSQL_PASSWORD=
      - MYSQL_PORT=3306
    volumes:
      - ./docker/mysql/dumps:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - "3366:3306"

  db_test:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=abter_test
      - MYSQL_DATABASE=abter_test
      - MYSQL_USER=abter_test
      - MYSQL_PASSWORD=abter_test
      - MYSQL_PORT=3306
    volumes:
      - ./docker/mysql/dumps:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    ports:
      - "3376:3306"

  memcached:
    image: memcached:alpine
    ports:
      - "11271:11211"

  redis:
    image: redis:alpine
    ports:
      - "6439:6379"

  mailcatcher:
    image: mailhog/mailhog
    ports:
      - "1085:1025"
      - "8085:8025"
    environment:
      - MH_HOSTNAME=localhost

  fpm:
    image: abtercms/php:74
    links:
      - db
      - db_test
      - memcached
      - redis
      - mailcatcher
    environment:
      - DIR_PRIVATE=/website/private
      - DIR_PUBLIC=/website/public
      - DIR_AUTH_CONFIG=/website/config/authorization
      - DIR_MIGRATIONS=/website/resources/migrations
      - DIR_LOGS=/website/tmp/logs
      - OAUTH2_PRIVATE_KEY_PATH=/website/private/private.key
      - OAUTH2_PUBLIC_KEY_PATH=/website/private/public.key
      - DB_HOST=db
      - DB_NAME=abter
      - DB_USER=abter
      - DB_PASSWORD=28T3pqyvKG3tEgsjE8Rj
      - DB_PORT=3306
    volumes:
      - .:/website
      - ./docker/php/conf.d/ast-off.ini:/usr/local/etc/php/conf.d/docker-php-ext-ast.ini:ro
      - ./docker/php/conf.d/zzz_020_general.ini:/usr/local/etc/php/conf.d/zzz_020_general.ini:ro
      - ./docker/php/conf.d/zzz_500_local.ini:/usr/local/etc/php/conf.d/zzz_500_local.ini:ro
    working_dir: /website

  cli:
    image: abtercms/php:74
    links:
      - db
      - db_test
      - memcached
      - redis
      - mailcatcher
    environment:
      - DIR_PRIVATE=/website/private
      - DIR_PUBLIC=/website/public
      - DIR_AUTH_CONFIG=/website/config/authorization
      - DIR_MIGRATIONS=/website/resources/migrations
      - DIR_LOGS=/website/tmp/logs
      - OAUTH2_PRIVATE_KEY_PATH=/website/private/private.key
      - OAUTH2_PUBLIC_KEY_PATH=/website/private/public.key
      - DB_HOST=db
      - DB_NAME=abter
      - DB_USER=abter
      - DB_PASSWORD=
      - DB_PORT=3306
    volumes:
      - .:/website
      - ./docker/php/conf.d/zzz_020_general.ini:/usr/local/etc/php/conf.d/zzz_020_general.ini:ro
      - ./docker/php/conf.d/zzz_500_local.ini:/usr/local/etc/php/conf.d/zzz_500_local.ini:ro
    working_dir: /website

  nginx:
    image: nginx
    links:
      - fpm
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - .:/website
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    working_dir: /website
