FROM php:8.0-fpm-alpine

RUN apk upgrade --update && apk add \
        coreutils \
        autoconf \
        build-base \
        freetype-dev \
        libjpeg-turbo-dev \
        libltdl \
        libmcrypt-dev \
        libpng-dev \
        icu-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        git \
        libsodium-dev \
        postgresql-dev \
    && docker-php-ext-install -j$(nproc) iconv intl pdo_mysql pdo_pgsql soap xsl zip bcmath \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd

RUN pecl install redis-5.3.3 \
    && pecl install xdebug-3.0.2 \
    && pecl install libsodium-2.0.23 \
    && pecl install mcrypt-1.0.4 \
    && pecl install ast-1.0.10 \
    && docker-php-ext-enable redis xdebug
