FROM php:8.0-fpm-alpine

RUN apk upgrade --update && apk add \
        coreutils \
        autoconf \
        build-base \
        freetype-dev \
        libjpeg-turbo-dev \
        libltdl \
        libmcrypt-dev \
        libpng-dev \
        icu-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        git \
        libsodium-dev \
        postgresql-dev \
        libmemcached-dev \
    && docker-php-ext-install -j$(nproc) iconv intl pdo_mysql pdo_pgsql soap xsl zip bcmath \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd

COPY bin/composer-install.sh /tmp/composer-install.sh

RUN chmod +x /tmp/composer-install.sh \
    && /tmp/composer-install.sh \
    && rm -f /tmp/composer-install.sh

# libsodium is not recognized by docker-php-ext-enable
RUN pecl install redis \
    && pecl install memcached \
    && pecl install xdebug \
    && pecl install libsodium \
    && pecl install mcrypt \
    && pecl install ast \
    && docker-php-ext-enable redis memcached xdebug mcrypt ast
